"""initial_migration

Revision ID: 22201248c0fb
Revises:
Create Date: 2023-05-14 20:26:03.247471+00:00

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "22201248c0fb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kucoin_triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_symbol", sa.String(), nullable=True),
        sa.Column("to_symbol", sa.String(), nullable=True),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("trigger_count", sa.Integer(), nullable=True),
        sa.Column("period_seconds", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kucoin_triggers")
    # ### end Alembic commands ###
