"""update transactions max count field

Revision ID: 1aaece15756a
Revises: 697771f5b2ff
Create Date: 2023-05-16 05:56:12.592381+00:00

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1aaece15756a"
down_revision = "697771f5b2ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kucoin_triggers", sa.Column("transactions_max_count", sa.Integer(), nullable=True))
    op.drop_column("kucoin_triggers", "transactions_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kucoin_triggers", sa.Column("transactions_count", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("kucoin_triggers", "transactions_max_count")
    # ### end Alembic commands ###
